language: java

env:
  matrix:
  - PLATFORM=railo42 TARGET=test-ci
  - PLATFORM=railo42 TARGET=build
  global:
  - ARTIFACTS_S3_BUCKET=downloads.presidecms.com
  - secure: jvsE21m7x0RdzxWGdbcxoxiCdXnUfhb654tkfbuK67DJ5/Suk3P1QfPSFpWpanuzm+X1kNzcrKnz84iTG+Me0m+ypd3eeHWL6e4qFyoYunpFxCxx0GPlto+bcZ8mARNt6HmTwTpsbwMpJxiP5c2DqTu85go5blaITmgpFlT/bkU=
  - secure: F6I7UIinztbSglyuvR1QxfNHmi3ZjsV9kqx0NeKm5zzAoYJWg5vF8/WMkn8NI80Q+89CRZwb56JPMedCLJndum6t7/NS1fpBW8/bP0FzRU+1/KvG0U99UiESnEAKcMGSgh5lq/74+sn0qApuTSVuSg9fsar/h3Gg5Xj0A+6Jias=
before_script:
- mysql -e 'create database preside_test;'

install: ant -f support/build/build.xml -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM install-ci-deps
script: ant -f support/build/build.xml -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM -Dbranch=$TRAVIS_BRANCH -Dtag=$TRAVIS_TAG $TARGET

notifications:
  email: false
  slack:
    secure: E4SXeyDjcKHLEZI4zyzsHW+2CXg/h1RNAmASsJ0t60q5r19b6uHR8dDvgbR2OIVN7bNVzX5xOjPb4Km2+YYrPbSktFeb4UV7LatGcPoFO3XKQyn+5Q9D2gcQCcWfBgqX4i74kqqXCvnACrAg7ALRmQSkOZUNaK6YtUu+KCkrXQ8=

deploy:
  provider: s3
  access_key_id: AKIAJ3PTU73IHOOZV3LQ
  secret_access_key:
    secure: quj9MxIlfx43l9S6CXcchbpsKd43DPkNyZIAOl3crQVz2iG7qQfYacgl9utgM66cl6ZEd4ZC24PcYAeD3Y9np8OmlYGXQ85ofI/pp7h9jsbL9Fyk2RjObTxmka/+vdKAI7mKw1GSZFQGPIsOKSFfKfHyqhL35Tk+xB1K4vM43fQ=
  bucket: downloads.presidecms.com
  local-dir: support/build/artifacts
  upload-dir: presidecms
  skip_cleanup: true
  on:
    repo: pixl8/Preside-CMS
    condition: "$TARGET = build"
    all_branches: true
